name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'docker-hello-world/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker-hello-world/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./docker-hello-world
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops_learning_app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops_learning_app:${{ github.sha }}
        platforms: linux/amd64,linux/arm64